// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfertyPracy.Database;

#nullable disable

namespace OfertyPracy.Migrations
{
    [DbContext(typeof(OfertyPracyDBcontext))]
    [Migration("20240531123944_V2.1")]
    partial class V21
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobOffers.Models.OfertyPracyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPublikacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStworzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWaznosci")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRekrutera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodzajUmowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytuł")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WymiarPracy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wynagrodzenie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OfertyPracy");
                });

            modelBuilder.Entity("OfertyPracy.Database.OfertyPracyBenefity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfertaPracyId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfertaPracyId");

                    b.ToTable("Benefity");
                });

            modelBuilder.Entity("OfertyPracy.Database.OfertyPracyWymagania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfertaPracyId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfertaPracyId");

                    b.ToTable("Wymagania");
                });

            modelBuilder.Entity("OfertyPracy.Database.OfertyPracyBenefity", b =>
                {
                    b.HasOne("JobOffers.Models.OfertyPracyModel", "OfertaPracy")
                        .WithMany("Benefity")
                        .HasForeignKey("OfertaPracyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfertaPracy");
                });

            modelBuilder.Entity("OfertyPracy.Database.OfertyPracyWymagania", b =>
                {
                    b.HasOne("JobOffers.Models.OfertyPracyModel", "OfertaPracy")
                        .WithMany("Wymagania")
                        .HasForeignKey("OfertaPracyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfertaPracy");
                });

            modelBuilder.Entity("JobOffers.Models.OfertyPracyModel", b =>
                {
                    b.Navigation("Benefity");

                    b.Navigation("Wymagania");
                });
#pragma warning restore 612, 618
        }
    }
}
